version: "3"

services:   
  jupyterlab:
    build: .
    container_name: python-study
    ports:
      - 8889:8888
    volumes:
      - ./:/home/jovyan/code
      # local host timezone & localtime info update
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - JUPYTER_TOKEN=easy
    user: root
  
volumes:
  code:
