version: "3.8"

services: 
  postgres:
    image: docker.io/library/postgres:latest
    container_name: db
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports: 
      - 54320:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgadmin:
    image: docker.io/dpage/pgadmin4
    container_name: pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 54330:80
    depends_on: 
      - postgres
    volumes:
      - ./pgadmin:/var/lib/pgadmin 

volumes:
  postgres:
  pgadmin:


  