version: "3.8"

services: 
  postgres:
    image: docker.io/library/postgres:latest
    container_name: db
    restart: always
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test
    ports: 
      - 5432:5432
    volumes:
      - ./data_db_local:/var/lib/postgresql/data

  pgadmin:
    image: docker.io/dpage/pgadmin4
    container_name: pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"
    depends_on: 
      - postgres
    volumes:
      - ./data_pgadmin:/var/lib/pgadmin 

volumes:
  local_pgdata:
  pgadmin-data: